config/routes.rb
Rails.application.routes.draw do

   resources :notes,  :sessions, :users  
   root 'users#index'
   
   get "/signin", to: "sessions#new"
   post "/sessions", to: "sessions#create"
   get "/signup", to: "users#new"
   delete '/signout', to: 'sessions#destroy'
   get "/auth/:provider/callback" => "notes#index"
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 } , :on => [ :create ]
  validates :password_confirmation, presence: true, :on =>[ :create ]

  has_many :notes
  
  private
    def create_remember_token
      self.remember_token ||= SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
   
      include NotesHelper

  before_filter :signed_in_user, only: [:create, :new, :edit, :update, :destroy]
  before_filter :check_note_owner, only: [:edit, :update, :destroy]
   def index
      @notes = current_user.notes
      unless request.env['omniauth.auth'].nil?
        @token_id = request.env['omniauth.auth']["credentials"]["token"]
        current_user.update(token_id: @token_id)
      end
      
      unless current_user.token_id.nil? 
        client = Google::APIClient.new
        client.authorization.access_token = current_user.token_id
        service = client.discovered_api('calendar', 'v3')
           @result = client.execute(
                                 :api_method => service.calendar_list.list,
                                 :parameters => {},
                                 :headers => {'Content-Type' => 'application/json'})
            
       end
      
    end
   
    def new
        @note = current_user.notes.build
    end 
   
    def create
        @note = current_user.notes.create note_params
        @note.save
         
       if @note.save
          client = Google::APIClient.new
          client.authorization.access_token = current_user.token_id
          puts current_user.token_id
          service = client.discovered_api('calendar', 'v3')
            event = {
                     'summary' => @note.title,
                     'description' => @note.note,
                     'start' => {'date' =>(DateTime.now+1.week).rfc3339.split("T")[0]},
                     'end' => {'date' => (DateTime.now+1.week).rfc3339.split("T")[0]}
                   }
             result = client.execute(:api_method => service.events.insert,
                        :parameters => {'calendarId' => 'primary'},
                        :body => JSON.dump(event),
                        :headers => {'Content-Type' => 'application/json'})
         
             print result.data.id
         end
       
        redirect_to notes_path
        
    end
   
    def show 
        @note = Note.find(params[:id])
    end 
   
    def edit
        @note = Note.find(params[:id])
    end
   
    def update
       @note = Note.find(params[:id])
       @note.update note_params
       redirect_to note_path
    end
    
    def destroy
       Note.find(params[:id]).destroy
       redirect_to notes_path
    end
   
   private 
    def note_params
       params.require(:note).permit(:title, :note)
    end 
end

app/controllers/omniauth_callbacks_controller.rb
#class Users::OmniauthCallbacksController < Users::OmniauthCallbacksController
 # def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
#      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)#

      #if @user.persisted?
       # flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      #  sign_in_and_redirect @user, :event => :authentication
     # else
    #    session["devise.google_data"] = request.env["omniauth.auth"]
   #     redirect_to new_user_registration_url
  #    end
 # end
#end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   def new
   end

   def create
         user=User.find_by(email: params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
           # Sign the user in and redirect to the user's show page.
          sign_in user
          redirect_to notes_path
       else
          # Create an error message and re-render the signin form.
          flash[:error]='Invalid email address/password combination'
          redirect_to signin_path
        end
    end
  

    def destroy
         sign_out
         redirect_to users_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def index
        @user = User.all
   end
   
   def show
        @user = User.find(params[:id])
   end

   def new
        @user = User.new
   end

   def create
        @user = User.new(user_params)
        if @user.save
              flash[:success] = "Welcome to MY_NoTE app!"
              sign_in @user
              redirect_to notes_path
         else
              flash[:error] = "Failed to create account.  Try again."
              redirect_to new_user_path
          end
    end

    def update
          @user = User.find(params[:id])
          @user.update_attributes(user_params)
          redirect_to @user
    end
    
    def google_oauth2
          @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

         if @user.persisted?
             flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
             sign_in_and_redirect @user, :event => :authentication
         else
              session["devise.google_data"] = request.env["omniauth.auth"]
              redirect_to new_user_registration_url
         end
     end

   private
     def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
     end
end
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper

	def check_note_owner
    note = current_user.notes.where(:id => params[:id]).first
    
    if note.nil?
      flash[:error] = "That's not yours!"
      redirect_to note_path(params[:id])
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

             # SessionHelper manages @current_user, that's the user currently
             # signed in.
             # signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
             # current_user is avilable in controllers and views!
             # This is an is an assignment, which we must define - see below
             # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

             # Authorization: signed_in_user is called in a before_filter
             # callback in each controller, see books/ingredients/recipe controllers
             # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
              # If not signed in, save current location in session object
              # to be able to redirect after successful sign in.
      session[:return_to] = request.url
              # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

               # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

             # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end
              # if current_user doesn't exist, check session cookie for user session
              # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>MyNotes</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>

       <%= yield %>

  </body>
</html>

app/views/notes/edit.html.erb
<h1 style="font-variant:small-caps;">Edit Your Note</h1>
  <%= form_for @note do |f| %>

     <%= label_tag(:title, "Title:") %>
     <%= f.text_field :title %></br>

     <%= label_tag(:Text, "Note") %>
     <%= f.text_area :note %></br>

     <%= f.submit "Submit" %>
  <% end %>
<%= link_to "Back to the notes", notes_path %>

app/views/notes/index.html.erb
 <div style="position:fixed; right:70px;top:80px; color:red;">
    <%= link_to "Connect to Google calendar", "/auth/google_oauth2" %>
</div>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
       <a  style="text-shadow:4px 4px 8px red ;" class="navbar-brand" href="#">MY NOTES</a>
       
       <%= link_to "Sign-out", signout_path, :method => :delete, :class => "btn btn-danger btn-sm navbar-right"%>
               
   </div>
  </div>
 </nav>
 <table id="table", class="table">
    <tr> 
      <th>NOte Title</th>
     </tr>
       <% @notes.each do |note| %>
       <tr>
          <td><%=link_to note.title, note_path(note)%></td>
          <td><%=link_to"Delete", note, method: :delete, data: {confirm: "Are you sure?"}%></td>
       </tr>  
     <% end %>
 </table>
   <%= link_to "New_note", new_note_path, :class => "btn btn-success btn-sm"%>

app/views/notes/new.html.erb
<h1 style= "font-variant:small-caps;">Add Your New Note:</h1>

<%= form_for @note do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
 
    <p id= ta5>
      <%= f.label :note %><br>
      <%= f.text_area :note %>
    </p>
 
    <p>
      <%= f.submit %>
    </p>
 <% end %>
 <%= link_to "Back To The Home Page", notes_path %>

app/views/notes/show.html.erb
<h1 style="font-variant:small-caps;">Review Page</h1>
 <div class="panel panel-default">
    <table id="tableshow">
       <tr>
         <th>Title</th>
         <th>Text</th>
       </tr>
       <tr>
         <td><%= @note.title %></td>
         <td><%= @note.note %></td>
       </tr>
    </table>
</div>
<%=link_to "Edit", edit_note_path %>
<%= link_to "Back To The Home Page", notes_path %>

app/views/users/index.html.erb
 <h1 style="font:italic small-caps bold 15px georgia;font-size:40px;" id="greeting">Welcome to My Notes site</h1>
	
   <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
       <a  style="text-shadow:4px 4px 8px red ;" class="navbar-brand" href="#">MY NOTES</a>
       
         <%= link_to "login", signin_path, :class => "btn btn-primary btn-sm navbar-right"%>
         <%= link_to "Signup", signup_path, :class => "btn btn-primary btn-sm navbar-right"%>
              
      </div>
   </nav>
 

app/views/users/new.html.erb
<h1 style= "font-variant:small-caps;">Sign up</h1>

<div class="row">
    <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
       <%= form_for(@user) do |f| %>
        <% unless @user.errors.count == 0   %>
        <div  class="alert alert-error">
              The form contains <%= pluralize(@user.errors.count, "error") %>.
          
          <% end %>
        <p id="signup">
        <%= f.label :name %>
        <%= f.text_field :name %></br>

        <%= f.label :email %>
        <%= f.text_field :email %></br>

        <%= f.label :password %>
        <%= f.password_field :password %></br>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %></br>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <%= link_to "back to the main",users_path%>
        </p>
      <% end %>
     </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
      <h3><%= @user.name %></h3>
      <h3><%= @user.email %></h3>
  </aside>
</div>